# Generated by Django 2.2.7 on 2019-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_X', models.FloatField()),
                ('loc_Y', models.FloatField()),
                ('uniqueID', models.CharField(max_length=255)),
                ('hectare', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('hectareNum', models.IntegerField()),
                ('age', models.CharField(max_length=255)),
                ('primaryColor', models.CharField(max_length=255)),
                ('highlightColor', models.CharField(max_length=255)),
                ('combiColor', models.CharField(max_length=255)),
                ('colorNotes', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('measurement', models.CharField(max_length=255)),
                ('specificLocation', models.CharField(max_length=255)),
                ('running', models.CharField(max_length=255)),
                ('chasing', models.CharField(max_length=255)),
                ('climbing', models.CharField(max_length=255)),
                ('eating', models.CharField(max_length=255)),
                ('foraging', models.CharField(max_length=255)),
                ('otherActivities', models.CharField(max_length=255)),
                ('kuks', models.CharField(max_length=255)),
                ('quaas', models.CharField(max_length=255)),
                ('moans', models.CharField(max_length=255)),
                ('tailFlags', models.CharField(max_length=255)),
                ('tailTwitches', models.CharField(max_length=255)),
                ('approaches', models.CharField(max_length=255)),
                ('indifferent', models.CharField(max_length=255)),
                ('runsFrom', models.CharField(max_length=255)),
                ('otherInteractions', models.CharField(max_length=255)),
                ('latLong', models.CharField(max_length=255)),
                ('zipcodes', models.CharField(max_length=255)),
                ('communityDistricts', models.IntegerField()),
                ('boroughBoundaries', models.IntegerField()),
                ('cityCouncilDistricts', models.IntegerField()),
                ('policePrecincts', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Squirrel',
            },
        ),
    ]
